/**
 * @TYPES
 * ==============================================
 * HOUSEHOLD
 */


export const MENU_FETCH_ALL = 'MENU_FETCH_ALL'

/**
 * @TYPES
 * ===============================================
 * AUTHENTICATE
 */
 export const AUTHENTICATION = 'AUTHENTICATION'
 export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR'
 export const UNAUTHORISED_ERROR = 'UNAUTHORISED_ERROR'
 /**
 * @TYPES
 * ===============================================
 * USER
 */

export const REGISTER_REQUEST = 'USERS_REGISTER_REQUEST'
export const REGISTER_SUCCESS =  'USERS_REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'USERS_REGISTER_FAILURE'
export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USER_BY_ID = 'FETCH_USER_BY_ID'
export const USER_ROLE_UPDATE = 'USER_ROLE_UPDATE'
export const USERS_ERROR = 'USERS_ERROR'
export const FETCH_ME = 'FETCH_ME'
export const PERMISSION = 'PERMISSION'

/**
 * @TYPES
 * ===============================================
 * ROLES AND PERMISSIONS
 */
 export const FETCH_ROLES = 'FETCH_ROLES'
 export const ADD_ROLE = 'ADD_ROLE'
 export const UPDATE_ROLE = 'UPDATE_ROLE'
 export const FETCH_PERMISSIONS = 'FETCH_PERMISSIONS'
 export const ROLE_ERROR = 'USERS_ERROR'
 export const PERMISSION_ERROR = 'USERS_ERROR'
 export const ROLE_DELETE = 'ROLE_DELETE'
 export const FETCH_ALL_REGISTERED_PATIENTS = 'FETCH_ALL_REGISTERED_PATIENTS'
 export const ERROR_FETCH_ALL_REGISTERED_PATIENTS = 'ERROR_FETCH_ALL_REGISTERED_PATIENTS'
 export const DELETE_ORGANISATION_UNIT = 'DELETE_ORGANISATION_UNIT'
 export const DELETE_ORGANISATION_UNIT_ERROR = 'DELETE_ORGANISATION_UNIT_ERROR'
/**
 * @TYPES
 * ===============================================
 * FORMBUILDER
 */
export const FORMTYPES_FETCH_ALL = 'FORMTYPES_FETCH_ALL'
export const FORM_CREATE = 'FORM_CREATE'
export const UPDATE_FORM_DATA = 'UPDATE_FORM_DATA'
export const FORMTYPES_FETCH_ALL_FORMS = 'FORMTYPES_FETCH_ALL_FORMS'
export const FORMTYPES_FETCH_SERVICES = 'FORMTYPES_FETCH_SERVICES'
export const FORMTYPES_FETCH_DOMAINS = 'FORMTYPES_FETCH_DOMAINS'
export const FORMTYPES_FETCH_BY_ID = 'FORMTYPES_FETCH_BY_ID'
export const FORMTYPES_CREATE_FORM = 'FORMTYPES_CREATE_FORM'
export const FORMTYPES_UPDATE = 'FORMTYPES_UPDATE'
export const FORMTYPES_DELETE = 'FORMTYPES_DELETE'
export const FORMTYPES_ERROR = 'FORMTYPES_ERROR'


export const FORM_SAVE_ENCOUNTER = 'FORM_SAVE_ENCOUNTER'
export const PROGRAM_FETCH_ALL = 'PROGRAM_FETCH_ALL'
export const FORM_FETCH_BY_ID = 'FORM_FETCH_BY_ID'
export const FORM_FETCH_ALL = 'FORM_FETCH_ALL'
export const FORM_UPDATE = 'FORM_UPDATE'
export const FORM_ERROR = 'FORM_ERROR'

/**
 * @TYPES
 * ==============================================
 * PATIENTS
 */

export const PATIENTS_FETCH_ALL = 'PATIENTS_FETCH_ALL'
export const PATIENTS_FETCH_BY_ID = 'PATIENTS_FETCH_BY_ID'
export const PATIENTS_CREATE = 'PATIENTS_CREATE'
export const PATIENTS_UPDATE = 'PATIENTS_UPDATE'
export const PATIENTS_DELETE = 'PATIENTS_DELETE'
export const PATIENTS_ERROR = 'PATIENTS_ERROR'
export const PATIENT_VITAL_SIGNS = 'PATIENT_VITAL_SIGNS'
export const PATIENT_LATEST_VITAL_SIGNS = 'PATIENT_LATEST_VITAL_SIGNS'
export const PATIENT_ALLERGIES = 'PATIENT_ALLERGIES'
export const PATIENT_LAB_ORDERS = 'PATIENT_LAB_ORDERS'
export const PATIENT_LATEST_MEDICATION_LIST = 'PATIENT_LATEST_MEDICATION_LIST'
export const PATIENT_ENCOUNTER_LIST = 'PATIENT_ENCOUNTER_LIST'
export const PATIENT_EXCLUSIVE_ENCOUNTER_LIST = 'PATIENT_EXCLUSIVE_ENCOUNTER_LIST'
export const CHECKEDIN_PATIENT_FETCH_ALL = 'CHECKEDIN_PATIENT_FETCH_ALL'
export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const PATIENT_UPDATE = "PATIENT_UPDATE"
export const PATIENT_DELETE = "PATIENT_DELETE"
export const PATIENT_CONSULTATION_HISTORY = 'PATIENT_CONSULTATION_HISTORY'
export const PATIENT_APPOINTMENTS = 'PATIENT_APPOINTMENTS'
export const PATIENT_RADIOLOGY_ORDERS = 'PATIENT_RADIOLOGY_ORDERS'

/**
 * @TYPES
 * ==============================================
 * HouseHold Member 
 */

 export const HOUSE_HOLD_MEMBER_CREATE_SERVICE = 'HOUSE_HOLD_MEMBER_CREATE_SERVICE'
 export const ERROR_HOUSE_HOLD_MEMBER_CREATE_SERVICE = 'ERROR_HOUSE_HOLD_MEMBER_CREATE_SERVICE'
 export const FETCH_HOUSE_HOLD_MEMBER = 'FETCH_HOUSE_HOLD_MEMBER'
 export const FETCH_HOUSE_HOLD = 'FETCH_HOUSE_HOLD'
 export const FETCH_HOUSEHOLD_SERVICE_HISTORY = 'FETCH_HOUSEHOLD_SERVICE_HISTORY'
export const FETCH_HOUSE_HOLD_MEMBER_BY_ID = 'FETCH_HOUSE_HOLD_MEMBER_BY_ID'
export const FETCH_HOUSE_HOLD_BY_ID = 'FETCH_HOUSE_HOLD_BY_ID'
export const FETCH_HOUSEHOLD_MEMBERS_BY_HOUSEHOLD_ID = 'FETCH_HOUSEHOLD_MEMBERS_BY_HOUSEHOLD_ID'




